### ISSUE TITLE
Issue in deleting a record

### ISSUE THREAD

**Issue by amousavii** [joisarjignesh/bigbluebutton#12]
when i delete a recorded meeting it changes the state of that recording to deleted,
but it is still on the server, how can i remove it completely ?

**Comment by joisarjignesh** [comment]
@amousavii  you are right after delete a  recorded meeting it just change state as deleted ..
recording will be deleted withing 9 days default configuration on bigblubutton server but you can custom as well..

so you need get recording list with only published state if you want to get only published record only try to change in [bigbluebutton.php](https://github.com/joisarjignesh/bigbluebutton/blob/master/config/bigbluebutton.php#L257)  any to published


`state => 'published'`

other wise 

```
\Bigbluebutton::getRecordings([
    'meetingID' => 'tamku',
    //'recordID' => 'a3f1s',
   'state' => 'published' // It can be a set of states separate by commas  
]);

```

**Comment by cod3r0k** [comment]
Thanks a lot. 

`
\Bigbluebutton::getRecordings([
    'meetingID' => 'tamku',
    //'recordID' => 'a3f1s',
   'state' => 'published' // It can be a set of states separate by commas  
]);
`

You mentioned that `It can be a set of states separate by commas  `, you mean that I must use it as an array? like below?
` 'state' => ['published' ,'unpublished',...]`

**Comment by SamuelWei** [comment]
> you mean that I must use it as an array? like below?

See the code comment and offical bbb api docs (https://docs.bigbluebutton.org/dev/api.html#getrecordings)
```php
         /**
         * if the recording is [processing|processed|published|unpublished|deleted].
         * The parameter state can be used to filter results. It can be a set of states separate by commas.
         * If it is not specified only the states [published|unpublished] are considered
         * (same as in previous versions). If it is specified as “any”,
         * recordings in all states are included.
         *
         *  var @string
         */
```

**Comment by cod3r0k** [comment]
@SamuelWei Thanks a lot

**Comment by cod3r0k** [comment]
Dear @SamuelWei , I successfully change a state of recording with recordID but files is not deleted directly. When they being deleted?
