### ISSUE TITLE
guestPolicy in create not passing to URL?

### ISSUE THREAD

**Issue by code-by-dwayne** [joisarjignesh/bigbluebutton#13]
I've added the hooks to both the official bbb api and this to allow guestPolicy settings to be passed during the Create Room method.

Since it requires an update to the BBB api, should I just include the changes here for reference or make a pull request that can be merged when the API is updated? I haven't made a pull request there yet.

Thanks,
Dwayne

**Comment by joisarjignesh** [comment]
@code-by-dwayne pl make a pull request here

**Comment by code-by-dwayne** [comment]
will do. Watch for it over the next week; have a bit of clean up to do, and I hadn't pulled since you did a commit the other day.
