### ISSUE TITLE
How to create invite link?

### ISSUE THREAD

**Issue by jcbolor** [joisarjignesh/bigbluebutton#14]
I want to make an invite link like greenlight. How can I do that?

**Comment by code-by-dwayne** [comment]
I have a model/controller for 'rooms' that stores all the room's settings, issues a 'create' command when the room is set up. One of the fields in my room table is the 'code' of the room, ie 'dwa-5th-rgh'. My route file has a /room/{roomID} and the room controller parses the info and does the join as mod or guest according to user rights.
