### ISSUE TITLE
How to generate keys?

### ISSUE THREAD

**Issue by thedardan** [joisarjignesh/bigbluebutton#15]
Hello, how to generate these params in conf file, or where to get them?

```
BBB_SECURITY_SALT=bbb_secret_key   
BBB_SERVER_BASE_URL=https://example.com/bigbluebutton/
```

**Comment by joisarjignesh** [comment]
first you need to install bigbluebutton on your own server.

[how to install bigbluebutton on digitalocean](
https://www.youtube.com/watch?v=D1iYEwxzk0M)

read this official bigbluebutton documentation  for more detail about bigbluebutton
 https://docs.bigbluebutton.org/2.2/install.html
