### ISSUE TITLE
Can I embed in my webApp or it needs to redirect to bigBlueButton anyway?

### ISSUE THREAD

**Issue by ShkelqimZ** [joisarjignesh/bigbluebutton#16]
I'd love to embed conference on my own site (in my project view), mine app's url. Is this possible?

**Comment by joisarjignesh** [comment]
@ShkelqimZ  yes can embed in your webApp using iframe but some of feature not working on iframe (i don't know)
read this thread https://groups.google.com/forum/#!topic/bigbluebutton-dev/ynnQJbMr4G4

**better to redirect into bigbluebutton anyway..**
