### ISSUE TITLE
Can we call a function when some body go out from the room?

### ISSUE THREAD

**Issue by cod3r0k** [joisarjignesh/bigbluebutton#17]
Dear All, How can we detect that anybody is not in the room (with hooks)? E.g. how can we get the duration of each user entrance? also some body maybe have loss internet connection. I want to call some function when anybody's connection is destroyed

**Comment by SamuelWei** [comment]
You could pull the api and check the attendees lists.  See https://docs.bigbluebutton.org/dev/api.html#getmeetinginfo
The duration of an attendee could be calulated by pulling the attendees list every x Minutes. Next create a model for meeting_attendees and with start and end datetime. If a new user is detected set start to now, and once a user is not is the list anymore, set end date.

You could also try to implement something like that with https://docs.bigbluebutton.org/dev/webhooks.html I once tried it and did't have a lot of success, but you can try. As far as I know this api isn't supporting hooks, right @joisarjignesh ?

**Comment by joisarjignesh** [comment]
@SamuelWei  only  Hooks create and destroy wrap into laravel based not fully testing just added here.

**Comment by joisarjignesh** [comment]
@cod3r0k as you said by @SamuelWei  follow the instruction.

**Comment by cod3r0k** [comment]
> You could pull the api and check the attendees lists. See https://docs.bigbluebutton.org/dev/api.html#getmeetinginfo
> The duration of an attendee could be calulated by pulling the attendees list every x Minutes. Next create a model for meeting_attendees and with start and end datetime. If a new user is detected set start to now, and once a user is not in the list anymore, set end date.
> 
> You could also try to implement something like that with https://docs.bigbluebutton.org/dev/webhooks.html I once tried it and did't have a lot of success, but you can try. As far as I know this api isn't supporting hooks, right @joisarjignesh ?

Thank you @SamuelWei , you mean that we must use Scheduling (https://laravel.com/docs/7.x/scheduling) in Laravel for that?




> @SamuelWei only Hooks create and destroy wrap into laravel based not fully testing just added here.
Thanks @joisarjignesh but I didn't get what you say.
