### ISSUE TITLE
The meeting ID that you supplied did not match any existing meetings

### ISSUE THREAD

**Issue by cod3r0k** [joisarjignesh/bigbluebutton#18]
Hi all,
When I want to join into one meeting, it showed me the below message `The meeting ID that you supplied did not match any existing meetings`

What's goes on? I create a meeting and then join to it...?

**Comment by cod3r0k** [comment]
@joisarjignesh @SamuelWei

**Comment by SamuelWei** [comment]
Could you please post a code snippet to better understand the issue. Thanks.

**Comment by joisarjignesh** [comment]
@SamuelWei  is right @cod3r0k please add join code here for better understanding..

**Comment by joisarjignesh** [comment]
i think issue is solved so i close this issue.
