### ISSUE TITLE
create meeting with no microphone access

### ISSUE THREAD

**Issue by cod3r0k** [joisarjignesh/bigbluebutton#19]
Dear all, I want to create a room which the end-user not share the microphone access and just listen.
I don't want a modal window which force end-user to select it's access. I want an access to just listen (like play a music which don't need any access and the end-user fastly join to the meeting and not wait for checking anything).  
I change settings.yml in (/usr/share/meteor/bundle/programs/server/assets/app/config)

```
    autoJoin: true
    listenOnlyMode: false
    forceListenOnly: false
    skipCheck: true
```

But the modal is also coming and the user must wait for just 3-5 second. I want to create a room with api which the end-user not see any modal and join fast to the meeting.

If the moderator change it's access to a microphone or moderator from attendee, on that moment the end-user try to access the microphone.

Could you help me in this moment for joining fast like as any other music website which load in just a millisecond?
@SamuelWei

**Comment by SamuelWei** [comment]
Hello @cod3r0k,

you can set the skipCheck to false and restrict the viewers permissions to use the microphone (via api or inside the room). You will still see a popup for a few seconds, but it will disappear after a few seconds.

Please have in mind that this is just an api wrapper for bbb. If you don't like the functionality of bbb please use their ticket system.

Greetings
Samuel

**Comment by joisarjignesh** [comment]
@SamuelWei give a best answer so close this issue and thanks for supporting @SamuelWei .
