### ISSUE TITLE
Name or other information of attendee

### ISSUE THREAD

**Issue by cod3r0k** [joisarjignesh/bigbluebutton#21]
Dear all, I want to check who are in each meeting. I don't have any idea how can we check each person by another. Each person logged into the meeting via his/her name and I can't pass any parameter like as ssid or the other ones. 
Therefore, I can't check somebody when he/she has the same name as the other

What should I do now?

**Comment by joisarjignesh** [comment]
you can pass userId on join meeting and also pass custom parameters ... 

```
\Bigbluebutton::join([
    'meetingID' => 'tamku',
    'userName' => 'disa',
    'password' => 'attendee', //which user role want to join set password here
    'redirect' => false, //it will not redirect into bigblueserver
    'userId' =>  "54575",
    'customParameters' => [  
       'foo' => 'bar',
       'key' => 'value'
    ]
]);
```
