### ISSUE TITLE
Can we set specific constrain on the number of video when creating a meeting?

### ISSUE THREAD

**Issue by cod3r0k** [joisarjignesh/bigbluebutton#23]
Hi, How are you? thank you so much for your consideration in advance

I want to set a different constraint when each person want to create a meeting. E.g one person has just 3 live camera and the other has just 8 live webcam.

**Comment by joisarjignesh** [comment]
i don't know about this..
try to ask this google group he will help you.
 https://groups.google.com/g/bigbluebutton-dev
