### ISSUE TITLE
How can we set each BBB secret info for each room?

### ISSUE THREAD

**Issue by cod3r0k** [joisarjignesh/bigbluebutton#24]
Hi everybody, I want to send each room (meeting) to specific BBB server. Could you help me to integrate and extend @joisarjignesh 's  library  for this improvement?

**Comment by joisarjignesh** [comment]
@cod3r0k if possible i will add this feature(multiple server configuration)

**Comment by joisarjignesh** [comment]
@cod3r0k  pl share more details about  what you want with example so can i easily understand........

**Comment by cod3r0k** [comment]
Dear @joisarjignesh , As you know, Scalelite is a good solution for BBB scalability. But when we want to scalable the BBB servers, we must set different setting and it was very hard (Also when we want recording). Therefore, I think that if we can create a specific room in specific server, so that we can scalable our structure (because each BBB has limitation of at most 200 concurrent member).
For example, I create a meeting 01 in server 01 and create meeting 02 in server 01 and create meeting in server 02.

**Comment by joisarjignesh** [comment]
@cod3r0k you need to updated package and then run  

`php artisan vendor:publish --tag=bigbluebutton-config --force `

forcefully update new config file

- for specific server room create or join try to used like that
```
Bigbluebutton::server('serverName')->create()
Bigbluebutton::server('serverName')->join()
```

**Comment by cod3r0k** [comment]
Dear @joisarjignesh , Thank you so much.

When we didn't define a server name, we switch to default server? isn't it?
I mean that if we do not use `Bigbluebutton::server('*****') ` , it use `Bigbluebutton:: ? (like before or not?)

**Comment by joisarjignesh** [comment]
@cod3r0k yes  if you not  used server method then it will switch into default server 
`Bigbluebutton:`:   //default server
`Bigbluebutton::server('server1') `//specific server

**Comment by cod3r0k** [comment]
@joisarjignesh  Thanks a lot

**Comment by cod3r0k** [comment]
Dear @joisarjignesh , I have a problem when implement your update.
![image](https://user-images.githubusercontent.com/36899025/92994608-1394f600-f511-11ea-9c07-f6e983035f63.png)
Please help me in this issue

**Comment by joisarjignesh** [comment]
used facades  class 

`use JoisarJignesh\Bigbluebutton\Facades\Bigbluebutton;`

not used  original class
` use JoisarJignesh\Bigbluebutton\Bbb;`

**Comment by cod3r0k** [comment]
> used facades class
> 
> `use JoisarJignesh\Bigbluebutton\Facades\Bigbluebutton;`
> 
> not used original class
> ` use JoisarJignesh\Bigbluebutton\Bbb;`

Thanks but I use it and the error occur with your suggested facades class. I'm not sure what's goes on. Could you help me? Do I need any changes anywhere?

**Comment by joisarjignesh** [comment]
@cod3r0k first update this package end then check namespace which is import on the top of controller 
`use JoisarJignesh\Bigbluebutton\Facades\Bigbluebutton;` 
you need to set on the top of controller.
