### ISSUE TITLE
Delete recording is not working

### ISSUE THREAD

**Issue by cod3r0k** [joisarjignesh/bigbluebutton#27]
Dear @joisarjignesh , I call deleteRecordings function but nothing is removed.
Also, I use https://github.com/createwebinar/bbb-download for having mp4 version of each videos. Could you help me how to remove them beside deleteRecordings  function?

**Comment by joisarjignesh** [comment]
@cod3r0k  already fixed this issue see https://github.com/joisarjignesh/bigbluebutton/issues/12

**Comment by cod3r0k** [comment]
Thanks and do you have any idea for my second request? @joisarjignesh

**Comment by cod3r0k** [comment]
Dear @joisarjignesh or @SamuelWei , Do you have any idea which I can integrate [ bbb-download](https://github.com/createwebinar/bbb-download) files which located at /var/www/bigbluebutton-default/download/meetingid/meetingid.mp4 ?

I want to call your function and delete both BBB playback and that file.
