### ISSUE TITLE
Change timeline of BBB for processing of recording

### ISSUE THREAD

**Issue by cod3r0k** [joisarjignesh/bigbluebutton#28]
How can we set a specific range of time for video processing (from raw to published version)?
I want to have meeting session in morning and each of them processing in the afternoon and night. 
Also, If we have a specific meeting session in the afternoon, could we cancel the video processing (prev. recordings)

@SamuelWei @joisarjignesh

**Comment by cod3r0k** [comment]
Dear @joisarjignesh , Don't you have any idea?

**Comment by joisarjignesh** [comment]
@cod3r0k i don't have any idea better to ask official bigbluebutton group

**Comment by cod3r0k** [comment]
Thanks a lot @joisarjignesh
