### ISSUE TITLE
get all server names from config file

### ISSUE THREAD

**Issue by cod3r0k** [joisarjignesh/bigbluebutton#32]
Dear @SamuelWei & @joisarjignesh 
How can we get all server names from config file in controller?

```
'servers' => [
       'server1' => [
           'BBB_SECURITY_SALT'    => '',
           'BBB_SERVER_BASE_URL'  => '',
       ],
 ]
```

**Comment by joisarjignesh** [comment]
@cod3r0k read this article 
https://scotch.io/tutorials/how-to-use-laravel-config-files

note : @cod3r0k  only ask this package related issue here ..

**Comment by thedardan** [comment]
@joisarjignesh @SamuelWei @cod3r0k 
If I have 3 servers defined in conf/bigbluebutton.php, how to know which server Im using to create and join meeting?
