### ISSUE TITLE
How can we get information of enter and exit time of each user during each meeting

### ISSUE THREAD

**Issue by cod3r0k** [joisarjignesh/bigbluebutton#33]
Dear All, I want to have some reports which related to each session. How can we logs of enter and exit time of each user during the each meeting?
Some user join into some meeting, but their internet or any other events (like closing a browser, turning off the electricity or etc.) cause that they leave each meeting. I want to have an excellent log for this. 

With Laravel, I can just log the login time and also logout time (if they came back and not closing the browser) and it is not sufficient.

Please help me in this moment.
@SamuelWei @joisarjignesh

**Comment by Beginner95** [comment]
@cod3r0k How do you identify each participant in the meeting?

**Comment by cod3r0k** [comment]
> @cod3r0k How do you identify each participant in the meeting?

With id of each users.

**Comment by joisarjignesh** [comment]
@cod3r0k you need to ask in offical package https://github.com/bigbluebutton/bigbluebutton

see this meeting info given by testing blindside networks
how can i  found which time user enter and which time user left the meeting  
```
"returncode": "SUCCESS",
"meetingName": "test meeting",
"meetingID": "tamku",
"internalMeetingID": "81af4af9a64bc631869406022afbe7e607cb597c-15018285159",
"createTime": "1601708285159",
"createDate": "Sat Oct 03 02:58:05 EDT 2020",
"voiceBridge": "583583611",
"dialNumber": "18632080022",
"attendeePW": "attendee",
"moderatorPW": "moderator",
"running": "true",
"duration": "540",
"hasUserJoined": "true",
"recording": "true",
"hasBeenForciblyEnded": "false",
"startTime": "1601708285184",
"endTime": "0",
"participantCount": "1",
"listenerCount": "0",
"voiceParticipantCount": "0",
"videoCount": "0",
"maxUsers": "0",
"moderatorCount": "1",
"attendees": {
"attendee": {
"userID": "545454",
"fullName": "Disa",
"role": "MODERATOR",
"isPresenter": "true",
"isListeningOnly": "false",
"hasJoinedVoice": "false",
"hasVideo": "false",
"clientType": "HTML5",
"customdata": {
"bbb_preferred_camera_profile": "low"
}
}
},
"metadata": {
"bn-userid": "test-install",
"bn-meetingid": "tamku",
"bn-priority": "20"
},
"isBreakout": "false"
```

**Comment by cod3r0k** [comment]
Dear @joisarjignesh , I think, we can get more information form recording xml. As you know, we can access this information which related to any activity during each session. Isn't it?
