### ISSUE TITLE
Do we have any meeting statistics (Blindside) for recorded session?

### ISSUE THREAD

**Issue by cod3r0k** [joisarjignesh/bigbluebutton#34]
I found a news which related to the founder's of BBB.
https://blindsidenetworks.com/2018/02/20/statistics-report/

They said that we can have statistics of each session in the recording files. Do we have this in this library?  Do you have any related solution and idea?

**Comment by joisarjignesh** [comment]
@cod3r0k  In this package we don't have meeting statistics functionality and i don't found api(meeting statistics) in official api documentation https://docs.bigbluebutton.org/dev/api.html

see this related question in bigbluebutton/bigbluebutton offical package
https://github.com/bigbluebutton/bigbluebutton/issues/5656

@cod3r0k i already told you first of better to ask in official package note in your mind this is a not official package but if i found any new api i will and this package..

**Comment by cod3r0k** [comment]
Thank you @joisarjignesh . OK, I will ask them and notify you if I reach any further update.

**Comment by joisarjignesh** [comment]
@cod3r0k ok

**Comment by ha3ant** [comment]
Is there any news?
