### ISSUE TITLE
Recording size

### ISSUE THREAD

**Issue by cod3r0k** [joisarjignesh/bigbluebutton#35]
Dear @joisarjignesh , Can we calculate the size of each recording record id?
The API get me some information but there is not any further information in documentation.
Do we need to use https://github.com/elsonwu/bbb-record-size ?

**Comment by joisarjignesh** [comment]
@cod3r0k it's read only but you can try (i don't know how to install and used this package)

**Comment by cod3r0k** [comment]
> @cod3r0k it's read only but you can try (i don't know how to install and used this package)

Thank you @joisarjignesh . As you mentioned in https://github.com/joisarjignesh/bigbluebutton#get-recordings , we can get recording items with `get recording` function. It has one parameter which related to the size. But there isn't any further information that what is this size? is it Byte? is it MB? or ... 
Because I check it's related directiory in `/var/bigbluebutton/published/presentation/###id###` and there are many conflict with that amount size. Do you know it or not?

**Comment by joisarjignesh** [comment]
@cod3r0k i don't know
