### ISSUE TITLE
Make Request on different bbb servers

### ISSUE THREAD

**Issue by mvHS24** [joisarjignesh/bigbluebutton#36]
Hi Joisarjignesh,
first of all many thanks about this wonderful package!

Maybe you could help me or give me a suggestion, i try to get meeting info from two different servers with big blue button, but I've not found the right yet.

The first idea is to ask to server1 with a Laravel Scheduled job, and after this one, change env bbb parameters to connect to server2 and make the same things, but all this, unfourtunately not work! Do you ever try a thing like this one?

Thanks a lot!

**Comment by joisarjignesh** [comment]
you can use helper or facade whatever you used.
using helper method.

```
bigbluebutton('server1')->getMeetingInfo([
    'meetingID' => 'tamku',
    'moderatorPW' => 'moderator' //moderator password set here
]);
```

like server2 to getting meeting info

```
bigbluebutton('server2')->getMeetingInfo([
    'meetingID' => 'tamku',
    'moderatorPW' => 'moderator' //moderator password set here
]);

```

or you can overwrite config as runtime(dynamic) 

``` 
config("bigbluebutton.servers.server1.BBB_SERVER_BASE_URL","server1url");
```
