### ISSUE TITLE
all() method need to be a bit changed!

### ISSUE THREAD

**Issue by cod3r0k** [joisarjignesh/bigbluebutton#37]
Dear @joisarjignesh , the all method showed me an error when there is not any online meeting on the server

```
ErrorException
count(): Parameter must be an array or an object that implements Countable
```

![image](https://user-images.githubusercontent.com/36899025/95810583-2a03bc80-0d1e-11eb-9611-01d5dd20069f.png)

**Comment by joisarjignesh** [comment]
@cod3r0k when there is a not any meetings then  everytime given the error or sometime?
