### ISSUE TITLE
Joining a meeting in new tab

### ISSUE THREAD

**Issue by cod3r0k** [joisarjignesh/bigbluebutton#38]
Dear @joisarjignesh , How can we join each meeting in new tab? is there any solution?

**Comment by cod3r0k** [comment]
Hi, Is there any solution for that? @SamuelWei @joisarjignesh

**Comment by cod3r0k** [comment]
Do you have any idea? @joisarjignesh

**Comment by SamuelWei** [comment]
@cod3r0k Most of your questions are not related to this API, this is the wrong place to ask basic php and html questions. 

This API is there to help you make api calls to a bbb-server. Everything else needs to be done with the software that is using this api, probably a laravel project. 
Some ideas:
1. Have a javascript in the frontend calling a laravel route, that return the join link. Recieve the url in js and open the url in a new window `window.open("https://bbb-server.tld/bigbluebutton/api/....", "_blank");` This could be blocked by some web browsers as it is the same way as popups work
2. Have the user click on a link and open the page in a new tab `<a href="{{ route('bbbmeeting.join',['id'=>xyz] }}" target="_blank">Join meeting xyz</a>` The link should go to a laravel controller, that is calling the bbb api and return a redirect to the join url or show a error message on failure.

**Comment by cod3r0k** [comment]
> @cod3r0k Most of your questions are not related to this API, this is the wrong place to ask basic php, html, js questions.
> 
> This API is there to help you make api calls to a bbb-server. Everything else needs to be done with the software that is using this api, probably a laravel project.
> 
> Some ideas:
> 
> 1. Have a javascript in the frontend calling a laravel route, that return the join link. Recieve the url in js and open the url in a new window `window.open("https://bbb-server.tld/bigbluebutton/api/....", "_blank");` This could be blocked by some web browsers as it is the same way as popups work
> 2. Have the user click on a link and open the page in a new tab `<a href="{{ route('bbbmeeting.join',['id'=>xyz] }}" target="_blank">Join meeting xyz</a>` The link should go to a laravel controller, that is calling the bbb api and return a redirect to the join url or show a error message on failure.

Hi @SamuelWei , I find a good solution :) 

I use this tag and my problem is solved! (`onclick="$('form').attr('target', '_blank');"`)
