### ISSUE TITLE
Rebuild a specific meeting ID with laravel-BBB api

### ISSUE THREAD

**Issue by cod3r0k** [joisarjignesh/bigbluebutton#39]
Dear @joisarjignesh , How can we rebuild specific meeting id with this api?

**Comment by cod3r0k** [comment]
؟ What's happened to this issue?

**Comment by cod3r0k** [comment]
Dear @joisarjignesh , Don't you want to add a api for rebuilding a specific meeting id?

**Comment by joisarjignesh** [comment]
@cod3r0k  pl share here rebuilding a specific meeting id documentation url so i will try to add api..

**Comment by joisarjignesh** [comment]
@cod3r0k  any progresss ?
