### ISSUE TITLE
Can we pass language of panel in joining step?

### ISSUE THREAD

**Issue by cod3r0k** [joisarjignesh/bigbluebutton#40]
Can we pass language of panel when we want to join as a user?

**Comment by cod3r0k** [comment]
For example the moderator language is English and one user like Chinese language.

**Comment by joisarjignesh** [comment]
you can pass custom parameter when user at join 

\Bigbluebutton::join([
    'meetingID' => 'tamku',
    'userName' => 'disa',
    'password' => 'attendee', //which user role want to join set password here
    'redirect' => false, //it will not redirect into bigblueserver
    'userId' =>  "54575",
    'customParameters' => [  
       'foo' => 'bar',
       'language' => 'english'
    ]
]);
