### ISSUE TITLE
Waiting room

### ISSUE THREAD

**Issue by cod3r0k** [joisarjignesh/bigbluebutton#41]
Hi, How can we have a waiting room like as we have in Greenlight?

**Comment by joisarjignesh** [comment]
not a related bigbluebutton package

**Comment by cod3r0k** [comment]
Dear @joisarjignesh , Doesn't it related to the `guestPolicy` parameter? 

It has three value (`ALWAYS_ACCEPT`, `ALWAYS_DENY`, and `ASK_MODERATOR`)

**Comment by joisarjignesh** [comment]
i don't know you pl ask on official package php https://github.com/bigbluebutton/bigbluebutton-api-php
