### ISSUE TITLE
Add hooksList Method

### ISSUE THREAD

**Issue by mrtdeh** [joisarjignesh/bigbluebutton#46]
You who worked hard, add this too.

**Comment by mostafaElbana** [comment]
\Bigbluebutton::join([
                        'meetingID' => $meeting_id,
                        'userId'=>$user->id,
                        'userName' => $user->name_ar,
                        'password' => $password,
                        'joinViaHtml5'=> true,
                        'avatarURL'=>$user->AvatarURL,
                        'webVoiceConf'=> [
                            'bbb_auto_join_audio'   => true,
                            'bbb_listen_only_mode'   => false,
                        ],
                        'customParameters' => ['userId' => $user->id]
                    ]);
                    cannot view user image and not joining the audio bridge automatically
                    what is problem ?
