### ISSUE TITLE
endCallbackUrl not working

### ISSUE THREAD

**Issue by smsonn** [joisarjignesh/bigbluebutton#5]
hello
endCallbackUrl not working.  
When it is the session it does not forward the link created during session creation. Is there a solution to this problem
```
\Bigbluebutton::create([
   'meetingID' => 'tamku',
   'meetingName' => 'test meeting',
   'attendeePW' => 'attendee',
   'moderatorPW' => 'moderator',
   'endCallbackUrl'  => 'www.example.com/callback',
]); 
```

**Comment by joisarjignesh** [comment]
End meeting callback URL will notify silently. User won't redirect to that page. Details: https://docs.bigbluebutton.org/dev/api.html#end-meeting-callback-url
If you want to redirect users to that page after meeting end then can use logoutURL
see this [thread](https://groups.google.com/forum/#!msg/bigbluebutton-dev/VvMxDk5SiJc/7yAN7eJjAAAJ)

```
\Bigbluebutton::create([
   'meetingID' => 'tamku',
   'meetingName' => 'test meeting',
   'attendeePW' => 'attendee',
   'moderatorPW' => 'moderator',
   'logoutUrl'  => 'www.example.com/callback',
]); 
```
if you don't want specify every time on create meeting  set logoutUrl in configuration file `config/bigbluebutton.php`

`   'logoutUrl'                          =>  'www.example.com/callback'`

**Comment by smsonn** [comment]
> سيتم إشعار عنوان URL لإنهاء الاتصال بصمت. لن يقوم المستخدم بإعادة التوجيه إلى تلك الصفحة. التفاصيل: https://docs.bigbluebutton.org/dev/api.html#end-meeting-callback-url إذا كنت ترغب في إعادة توجيه المستخدمين إلى هذه الصفحة بعد انتهاء الاجتماع ، فيمكن استخدام logoutURL راجع هذا [الموضوع](https://groups.google.com/forum/#!msg/bigbluebutton-dev/VvMxDk5SiJc/7yAN7eJjAAAJ) [](https://docs.bigbluebutton.org/dev/api.html#end-meeting-callback-url)
> 
> [](https://groups.google.com/forum/#!msg/bigbluebutton-dev/VvMxDk5SiJc/7yAN7eJjAAAJ)
> 
> ```
> \Bigbluebutton::create([
>    'meetingID' => 'tamku',
>    'meetingName' => 'test meeting',
>    'attendeePW' => 'attendee',
>    'moderatorPW' => 'moderator',
>    'logoutUrl'  => 'www.example.com/callback',
> ]); 
> ```
> 
> إذا كنت لا تريد تحديد كل مرة عند إنشاء تسجيل الخروج تعيين الاجتماع في ملف التكوين `config/bigbluebutton.php`
> 
> ` 'logoutUrl' => 'www.example.com/callback'`
> 
> إذا كنت تريد اختبار webhook الاستماع اختبار ل endCallbackUrl [هنا](https://webhook.site/)

it's working thank you so much

**Comment by smsonn** [comment]
> End meeting callback URL will notify silently. User won't redirect to that page. Details: https://docs.bigbluebutton.org/dev/api.html#end-meeting-callback-url
> If you want to redirect users to that page after meeting end then can use logoutURL
> see this [thread](https://groups.google.com/forum/#!msg/bigbluebutton-dev/VvMxDk5SiJc/7yAN7eJjAAAJ)
> 
> ```
> \Bigbluebutton::create([
>    'meetingID' => 'tamku',
>    'meetingName' => 'test meeting',
>    'attendeePW' => 'attendee',
>    'moderatorPW' => 'moderator',
>    'logoutUrl'  => 'www.example.com/callback',
> ]); 
> ```
> 
> if you don't want specify every time on create meeting set logoutUrl in configuration file `config/bigbluebutton.php`
> 
> ` 'logoutUrl' => 'www.example.com/callback'`
> 
> if you want to test webhook listen test for endCallbackUrl [here](https://webhook.site/)

it's working thank you so much
