### ISSUE TITLE
not working in my laravel version 6.x

### ISSUE THREAD

**Issue by MehranLabour** [joisarjignesh/bigbluebutton#50]
```
 "php": "^7.2",
  "laravel/framework": "^6.2",
 "joisarjignesh/bigbluebutton": "^1.1", v1.1.8
```

  after fresh install of this package and publish config file  and insert `BBB_SECURITY_SALT` and `BBB_SERVER_BASE_URL` in the .end file i tried to test my BBB server with below code

```
dd(\Bigbluebutton::isConnect()); //false
```

but result is false,
i have another project laravel 5.5.* version and works fine with your package  `( "joisarjignesh/bigbluebutton": "^1.1",
)`.

i dont know whats wrong here when package installed in laravel version 6.2 its not working ,

any help will be appreciated

**Comment by joisarjignesh** [comment]
@MehranLabour  i checked on laravel version 6.2  it' working make sure you have to read installation step of this package ..
