### ISSUE TITLE
Auto callback from server (not joined user) after ending each meeting session vs Hooks

### ISSUE THREAD

**Issue by cod3r0k** [joisarjignesh/bigbluebutton#53]
Dear @joisarjignesh , Thanks for your great lib. 
Is there any way which we set on each session that call specific URL after each session is ended? (It is different from the callbackURL which we can set in join session). I want this option which call from server and not depends on the user.

Is there any thing about this? I think the Hook is similar but do you have any option? Do you suggest me the Hook?

**Comment by joisarjignesh** [comment]
@cod3r0k  you can do using hooks so please read docs https://docs.bigbluebutton.org/dev/webhooks.html
