### ISSUE TITLE
join the meeting

### ISSUE THREAD

**Issue by cod3r0k** [joisarjignesh/bigbluebutton#6]
Hi, I deal with simple and big issue! 
When I want to join to the meeting, I found the below error:

`
BadMethodCallException
Method Illuminate\Routing\ResponseFactory::to does not exist.
`

my code is the same as the tutorial but it doesn't work well.

`

		return response()->to(
			 Bigbluebutton::join([
				'meetingID' => 'tamku',
				'userName' => 'disa',
				'password' => 'attendee', //which user role want to join set password here
				//'redirect' => false, //it will not redirect into bigblueservr
			 ])
		)
`

**Comment by joisarjignesh** [comment]
use **redirect()** helper instead of **response()** helper it's mistake in docs 

i just updated my docs... thanks 

now try this code..

```
return redirect()->to(
		 Bigbluebutton::join([
			'meetingID' => 'tamku',
			'userName' => 'disa',
			'password' => 'attendee', //which user role want to join set password here
			//'redirect' => false, //it will not redirect into bigblueservr
		 ])
	);
```

**Comment by cod3r0k** [comment]
> use **redirect()** helper instead of **response()** helper it's mistake in docs
> 
> i just updated my docs... thanks
> 
> now try this code..
> 
> ```
> return redirect()->to(
> 		 Bigbluebutton::join([
> 			'meetingID' => 'tamku',
> 			'userName' => 'disa',
> 			'password' => 'attendee', //which user role want to join set password here
> 			//'redirect' => false, //it will not redirect into bigblueservr
> 		 ])
> 	);
> ```

Thanks, it was resolved.
