### ISSUE TITLE
Update meta data of recording 

### ISSUE THREAD

**Issue by cod3r0k** [joisarjignesh/bigbluebutton#61]
Dear All, How can we have **update recording** ?
https://docs.bigbluebutton.org/dev/api.html#updaterecordings

With this function, we can update our meta data of recordings

**Comment by joisarjignesh** [comment]
@cod3r0k  this package depends on this package https://github.com/bigbluebutton/bigbluebutton-api-php 
currently, this package does not provide this feature https://docs.bigbluebutton.org/dev/api.html#updaterecordings
so please request this feature into this package https://github.com/bigbluebutton/bigbluebutton-api-php

**Comment by cod3r0k** [comment]
Dear @cod3r0k, 
OK, I know what you mean, but I think we could extend that simultaneously.

**Comment by cod3r0k** [comment]
Dear @joisarjignesh , It's done now @ https://github.com/bigbluebutton/bigbluebutton-api-php/blob/master/src/BigBlueButton.php#L359

**Comment by joisarjignesh** [comment]
@cod3r0k  done
