### ISSUE TITLE
BigBlueButton\Parameters\CreateMeetingParameters::isAllowModsToEjectCameras(): Return value must be of type bool, null returned

### ISSUE THREAD

**Issue by doaaAbdelfatah** [joisarjignesh/bigbluebutton#63]

**Comment by doaaAbdelfatah** [comment]
Since the last composer update this code is not working according to bigbluebutton APIS updates

**Comment by AIahmedibrahim98** [comment]
I have same problem >>

**Comment by joisarjignesh** [comment]
I have already sent pr for this issue once he accepts it will resolve the issue.
https://github.com/bigbluebutton/bigbluebutton-api-php/pull/174

**Comment by sualko** [comment]
@joisarjignesh is there a reason that you moved back from https://github.com/littleredbutton/bigbluebutton-api-php to the official api? I think our fork does not have this issue.

**Comment by joisarjignesh** [comment]
@sualko already I think on the next release I will use https://github.com/littleredbutton/bigbluebutton-api-php this package instead of official but currently, I am busy with my own task.

**Comment by sualko** [comment]
Nice to hear, but no pressure. I was just curious if we can make anything better. Sorry for the noise in this issue.

**Comment by drojo4appes** [comment]
I am having the same issue,  any updates on this?

**Comment by joisarjignesh** [comment]
@sualko please approve my pull request https://github.com/littleredbutton/bigbluebutton-api-php/pull/111 so I can integrate into my package.

**Comment by codingear** [comment]
I have same problem, help me :(

**Comment by joisarjignesh** [comment]
> I have same problem, help me :(

once he my approved the request all bugs are fixed and release new version.

**Comment by joisarjignesh** [comment]
@codingear , @moez-aumet , @doaaAbdelfatah , @AIahmedibrahim98 , @doaaAbdelfatah 

released a new version and try to fixed all the issue so please check if you have any please let me know

**Comment by joisarjignesh** [comment]
> @joisarjignesh is there a reason that you moved back from https://github.com/littleredbutton/bigbluebutton-api-php to the official api? I think our fork does not have this issue.

now I integrate best package

**Comment by codingear** [comment]
**Thank you very much**, I am very grateful you have saved me.
