### ISSUE TITLE
latest version not work in laravel 8

### ISSUE THREAD

**Issue by mortezapiri** [joisarjignesh/bigbluebutton#65]
in previous versions
`dd(\Bigbluebutton::isConnect()); //is true`
in this version is false, also tested `\Bigbluebutton::all();` give exception.

**Comment by codingear** [comment]
Could you solve it? or is there any way to integrate another library to work in laravel. Thank you

**Comment by joisarjignesh** [comment]
@codingear currently I m integrating a new package for bigbluebutton in my package.

you can use this package in laravel.
https://github.com/littleredbutton/bigbluebutton-api-php

**Comment by ThalisGaeta** [comment]
I'm having the same problem.  I would be happy if you sould it :)

**Comment by joisarjignesh** [comment]
@ThalisGaeta and @codingear, @mortezapiri i release new version please check if you any issue let me know .
