### ISSUE TITLE
moderatorPassword is not a valid property

### ISSUE THREAD

**Issue by abolfazlnorzad** [joisarjignesh/bigbluebutton#69]
hi
I get an error when I try to create a new meeting
`   bigbluebutton()->create([
        'meetingID' => 'tamku',
        'meetingName' => 'test meeting',
        'attendeePW' => 'attendee',
        'moderatorPW' => 'moderator',
        'endCallbackUrl'  => 'www.example.com/callback',
        'logoutUrl' => 'www.example.com/logout',
    ]);`

![image](https://user-images.githubusercontent.com/69985608/197594853-6b3ffcfd-d5a2-4dad-95b1-312b13f598dd.png)

**Comment by Wesley-Sinde** [comment]
I have the same error, someone with a solution

**Comment by joisarjignesh** [comment]
@SamuelWei can you help me how to solve this issue?

**Comment by SamuelWei** [comment]
Hi everyone,

In your initMeeting you are calling setModeratorPassword, this is deprecated in littleredbutton since 4.3 and will be remove d in 5.0. The new function is setModeratorPW However you are not using semver in your composer file but dev-master, so you will always have the latest version and possible breaking changes!

Greetings
Samuel

**Comment by joisarjignesh** [comment]
@Wesley-Sinde @anthonyvage now i fixed that issue pl check and let me know if you still getting issue..
Note: before check please packages using composer

**Comment by joisarjignesh** [comment]
> Hi everyone,
> 
> In your initMeeting you are calling setModeratorPassword, this is deprecated in littleredbutton since 4.3 and will be remove d in 5.0. The new function is setModeratorPW However you are not using semver in your composer file but dev-master, so you will always have the latest version and possible breaking changes!
> 
> Greetings Samuel

thanks
