### ISSUE TITLE
The session continues to run after the end of time

### ISSUE THREAD

**Issue by smsonn** [joisarjignesh/bigbluebutton#7]
The session continues to run after the end of time. The session should automatically close when the session time ends and this does not happen. please help

**Comment by joisarjignesh** [comment]
@smsonn  

> Normally, the BigBlueButton server will end the meeting when either (a) the last person leaves (it takes a minute or two for the server to clear the meeting from memory) or when the server receives an end API request with the associated meetingID (everyone is kicked and the meeting is immediately cleared from memory).
> 
> BigBlueButton begins tracking the length of a meeting when it is created. If duration contains a non-zero value, then when the length of the meeting exceeds the duration value the server will immediately end the meeting (equivalent to receiving an end API request at that moment).

read officially documentation of [create a meeting](https://groups.google.com/forum/#!searchin/bigbluebutton-setup/end$20meeting$20after$20duration|sort:date/bigbluebutton-setup/6f8J90elaDk/tXPsUgx4FAAJ)  

read this thread [Duration of a meetings exceeded](https://groups.google.com/forum/#!searchin/bigbluebutton-setup/end$20meeting$20after$20duration|sort:date/bigbluebutton-setup/6f8J90elaDk/tXPsUgx4FAAJ)

**Comment by smsonn** [comment]
The problem has been resolved. It was because of duration of  function.
'duration' => $duration,
thanks a lot
