### ISSUE TITLE
Support Laravel 9/10

### ISSUE THREAD

**Issue by paulorlima9** [joisarjignesh/bigbluebutton#75]
Problem 1
    - joisarjignesh/bigbluebutton[v1.0.7, ..., v1.1.4] require illuminate/support ^5.5|^6|^7 -> found illuminate/support[v5.5.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6] but these were not loaded, likely because it conflicts with another require.
    - joisarjignesh/bigbluebutton[v1.1.5, ..., v1.2.5] require illuminate/support ^5.5|^6.0|^7.0|^8.0 -> found illuminate/support[v5.5.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - joisarjignesh/bigbluebutton[v2.1.0, ..., v2.4.3] require illuminate/support ^5.5|^6.0|^7.0|^8.0|^9.0 -> found illuminate/support[v5.5.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.4] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires joisarjignesh/bigbluebutton * -> satisfiable by joisarjignesh/bigbluebutton[v1.0.7, ..., v1.2.5, v2.1.0, ..., v2.4.3].

**Comment by paulorlima9** [comment]
https://github.com/joisarjignesh/bigbluebutton/pull/74

**Comment by joisarjignesh** [comment]
@paulorlima9  this package now suport laravel 10
