### ISSUE TITLE
undefined method isConnect()

### ISSUE THREAD

**Issue by sourceforest2** [joisarjignesh/bigbluebutton#76]
Hello,

After meticulously following the instructions provided in the tutorial, I installed the package on LARAVEL 9, but unfortunately encountered the following error message.

`Call to undefined method BigBlueButton\BigBlueButton::isConnect()`

My test script : 
```
Route::get('/test', function () {
    dd(Bigbluebutton::isConnect()); //default
});
```

Thank!

**Comment by joisarjignesh** [comment]
you  need to import this facade class on the top file like this in the web.php

`use JoisarJignesh\Bigbluebutton\Facades\Bigbluebutton;`

```
Route::get('/test', function () {
    dd(Bigbluebutton::isConnect()); //default
});
```

**Comment by sourceforest2** [comment]
Thank for prompt reply, but I get the same error even if I add this on top
