### ISSUE TITLE
It does not install on Laravel 10

### ISSUE THREAD

**Issue by shahrestani** [joisarjignesh/bigbluebutton#77]
say:
Your requirements could not be resolved to an installable set of packages.
Problem 1
- joisarjignesh/bigbluebutton[v2.4.0, ..., v2.4.3] require illuminate/support ^5.5|^6.0|^7.0|^8.0|^9.0 -> found illuminate/support[v5.5.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0
.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.15] but these were not loaded, likely because it conflicts with another require.
- joisarjignesh/bigbluebutton v2.4.4 requires littleredbutton/bigbluebutton-api-php dev-master -> found littleredbutton/bigbluebutton-api-php[dev-master] but it does not match your minimum-stability.
- Root composer.json requires joisarjignesh/bigbluebutton ^2.4 -> satisfiable by joisarjignesh/bigbluebutton[v2.4.0, ..., v2.4.4].

**Comment by joisarjignesh** [comment]
@shahrestani now check on laravel 10

**Comment by shahrestani** [comment]
The problem has been solved, thank you.
