### ISSUE TITLE
Can I verify a user on BBB with FaceID?

### ISSUE THREAD

**Issue by Khudayberdiyev0022** [joisarjignesh/bigbluebutton#79]
Hello, I need to compare the user with the image in the profile and webcam. Do I need to use a separate package for this or is it already in this package? I couldn't find it in the package documentation.

**Comment by joisarjignesh** [comment]
@Khudayberdiyev0022 it's not available in this package use other package.

**Comment by Khudayberdiyev0022** [comment]
@joisarjignesh Thanks
