### ISSUE TITLE
Could we check active tab browser?

### ISSUE THREAD

**Issue by cod3r0k** [joisarjignesh/bigbluebutton#8]
Hi, I want to check some participants' status. 
For example, I want to check which participants' browser is active and not changed during each session.

**Comment by joisarjignesh** [comment]
you can get all information including the list of attendees as well as start and end times

you can set userId on join for specific user identify.

```
\Bigbluebutton::join([
    'userId'  => 'aksara',
    'meetingID'  => 'tamku',
    'userName'  => 'disa',
    'password'  => 'attendee'
 ]);

```

so you can get specific attendee user information by using [getMeetingInfo](https://github.com/joisarjignesh/bigbluebutton#get-meeting-info) Method..


```
$meeting = Bigbluebutton::getMeetingInfo([
    'meetingID' => 'tamku',
    'moderatorPW' => 'moderator' //moderator password set here
]);

```


```
attendees": {
 "attendee": [
    {
      "userID": "xyz",
      "fullName": "Disa",
      "role": "MODERATOR",
      "isPresenter": "false",
      "isListeningOnly": "false",
      "hasJoinedVoice": "false",
      "hasVideo": "false",
      "clientType": "HTML5"
   }, 
  {
      "userID": "aksara",
      "fullName": "Jignesh",
      "role": "MODERATOR",
      "isPresenter": "true",
      "isListeningOnly": "true",
      "hasJoinedVoice": "false",
      "hasVideo": "false",
      "clientType": "HTML5"
   }
 ]
},

```

**Comment by cod3r0k** [comment]
Hi, No I want to achieve the status of the student (e.g.  he/she is changing hist browser bigbluebutton session tab or not) to know that if student just opening the session and goes to the WWW or not. 
I just want to check which student is online and just opening the bigbluebutton session tab and not goes over the WWW. 

I search over the internet and found http://jsfiddle.net/meehanman/40edh944/  or https://stackoverflow.com/questions/19519535/detect-if-browser-tab-is-active-or-user-has-switched-away/19519701  .

But I don't have an idea to integrate it over BBB and this framework. Could you help me?

**Comment by joisarjignesh** [comment]
**he/she is changing his/her browser bigbluebutton session tab or no**t 
if you want to know then bigbluebutton add on iframe and add this two (implement) condition on your application(wesbsite) 
http://jsfiddle.net/meehanman/40edh944/
and 
https://stackoverflow.com/questions/19519535/detect-if-browser-tab-is-active-or-user-has-switched-away/19519701

i don't know you get a proper result or but you try...

**Comment by cod3r0k** [comment]
for example, I'm student and you are host/ teacher.

I'm login into the class but minimize the browser or change the tab of the browser and go to WWW and done another task and not listen directly to the class. Therefore, if there is an option for you (teacher) which could control each student with some flag or some color or any other emoji for each online user and get the result of (http://jsfiddle.net/meehanman/40edh944/), It could be very well... 

I want to track students and help teachers to manage better the class

Do you have any idea? Could help me?

**Comment by joisarjignesh** [comment]
@cod3r0k  i already give you  my best idea please try.
if you want  more information about your track students feature ask here on github offically bigbluebutton  package
https://github.com/bigbluebutton/bigbluebutton/

or ask on google groups here 
https://groups.google.com/forum/#!forum/bigbluebutton-setup
https://groups.google.com/forum/#!forum/bigbluebutton-dev

**Comment by cod3r0k** [comment]
> **he/she is changing his/her browser bigbluebutton session tab or no**t
> if you want to know then bigbluebutton add on iframe and add this two (implement) condition on your application(wesbsite)
> http://jsfiddle.net/meehanman/40edh944/
> and
> https://stackoverflow.com/questions/19519535/detect-if-browser-tab-is-active-or-user-has-switched-away/19519701
> 
> i don't know you get a proper result or but you try...

Thanks a lot. But as you know, I want to check all participants in moderator access. 
Therefore, you mean that I do some programming for that? isn't it?  for e.g. I handle each participants with it's login authentication and list them in BBB moderator session?  

Also, Could you help me how to have a section for this purpose in BBB session? Also how can we have it in just moderator session and not viewer or participants view BBB session ?
