### ISSUE TITLE
 Create meeting Error

### ISSUE THREAD

**Issue by ascanipek** [joisarjignesh/bigbluebutton#80]
When I try to create a meeting I get the following error: 
"No parent meeting ID was provided for the breakout room".

My Code Here: 
$isCreated = \Bigbluebutton::create([
            'meetingID' => $meetingID,
            'meetingName' => $request->meetingName,
            'attendeePW' => $request->attendeePW,
            'moderatorPW' => $request->moderatorPW,
            'maxParticipants' => 3,
            'record' => TRUE,
   ]);

The code that worked when I first try, it started giving this error after a while and I can't solve it. I would be grateful if you could help me.

**Comment by joisarjignesh** [comment]
@ascanipek now check before check pl update composer then check

**Comment by ascanipek** [comment]
Thanks @joisarjignesh but i dont understand çözüldü you explain ☺️

**Comment by ascanipek** [comment]
@joisarjignesh I have updated it to version 2.6, but the problem was not solved. I still get this response after the create request: 
No parent meeting ID was provided for the breakout room

**Comment by joisarjignesh** [comment]
@ascanipek share your code here .

**Comment by ascanipek** [comment]
public function createMeeting(Request $request){
        // return $request;
        $meeting = DB::table('meetings')->select('c_id', 'lawyer')->where('id', $request->id)->get();
        $meetingID = $request->id . '_' . $meeting[0]->lawyer . '_' . $meeting[0]->c_id;
        
        $isCreated = Bigbluebutton::create([
            'meetingID' => $meetingID,
            'meetingName' => $request->meetingName,
            'attendeePW' => $request->attendeePW,
            'moderatorPW' => $request->moderatorPW,
            'maxParticipants' => 3,
            'record' => TRUE,
            // 'duration' => 'buraya süre girilebilir',
        ]);
        return $isCreated; // this return "No parent meeting ID was provided for the breakout room"
        if($isCreated['returncode'] == 'SUCCESS'){
            $isUpdate = DB::table('meetings')
                    ->where('id', $request->id)
                    ->update([
                        'is_created' => 1,
                        'meeting_id' => $meetingID,
                        'name' => $request->meetingName,
                        'attendeePW' => $request->attendeePW,
                        'moderatorPW' => $request->moderatorPW,
                    ]);
            if($isUpdate)
                return [
                    'status' => '200',
                    'msg' => 'Success'
                ];
            else
                return [
                    'status' => '500',
                    'msg' => 'DB Error'
                ];  
        }
        else{
            return [
                'status' => '418',
                'msg' => $isCreated
            ];
        }
    }

**Comment by joisarjignesh** [comment]
`use BigBlueButton\Parameters\CreateMeetingParameters;`
add this line on top 

```
  $meetingParams = new CreateMeetingParameters($meetingID , $request->meetingName);
  $meetingParams->setAttendeePW($request->attendeePW);
  $meetingParams->setModeratorPW($request->moderatorPW);
  $isCreated = Bigbluebutton::create($meetingParams);
```

check is it working or not

**Comment by ascanipek** [comment]
Thanks it worked this way. But what is the reason, why did the package not work with its default methods?

**Comment by joisarjignesh** [comment]
@ascanipek from myside works fine i don't know why not working your side but finally working this way 
i used this code behind or you are using my default method here also.

**Comment by ascanipek** [comment]
Thanks

**Comment by joachimdieterich** [comment]
I think it's an issue in Scalelite. We opened an [issue](https://github.com/bigbluebutton/bigbluebutton/issues/18961 ).

**Comment by joisarjignesh** [comment]
@joachimdieterich yes you are right. thanks for the inform here.

**Comment by Ithanil** [comment]
@joachimdieterich It is not an issue in Scalelite, but in BigBlueButton itself though.
