### ISSUE TITLE
BBB bannerText shows "false". Wrong config param is used.

### ISSUE THREAD

**Issue by joachimdieterich** [joisarjignesh/bigbluebutton#83]
Please  change 

`$meetingParams->setBannerText(
            $request->get('bannerText', config('bigbluebutton.create.webcamsOnlyForModerator', null))
        );`

in `src/Services/InitMeeting.php` line  87-89 to 

`$meetingParams->setBannerText(
            $request->get('bannerText', config('bigbluebutton.create.bannerText', null))
        );`

**Comment by joisarjignesh** [comment]
@joachimdieterich  done

**Comment by joachimdieterich** [comment]
Thank you!
