### ISSUE TITLE
endCallbackUrl not working

### ISSUE THREAD

**Issue by albertobenavides** [joisarjignesh/bigbluebutton#85]
Checked on POSTMAN and the listener I have created did what the route is inteded, but the bbb callback function is not triggering it. VerifyCSRFToken is also correct.

Does anyone faces the same problem?

**Comment by joisarjignesh** [comment]
note: when moderator end a meeting then endCallBackUrl will call if you pass the right url. 
pl check here i already tested working both logoutUrl and endCallBackUrl

https://webhook.site

let me know if you have any issue.

**Comment by albertobenavides** [comment]
Thank you, @joisarjignesh, it was a CSRF problem after all. Keep the good work going :)
