### ISSUE TITLE
New in bigblue button 

### ISSUE THREAD

**Issue by salmazz** [joisarjignesh/bigbluebutton#88]
i want to add bigblue button in my app i need to know 
BBB_SECURITY_SALT=bbb_secret_key   
BBB_SERVER_BASE_URL=https://example.com/bigbluebutton/
where i can get those values?

**Comment by joisarjignesh** [comment]
@salmazz you have to setup your own bigbluebutton server.
read this article https://docs.bigbluebutton.org/development/guide/
