### ISSUE TITLE
How to use bigbluebutton.properties?

### ISSUE THREAD

**Issue by princerafid01** [joisarjignesh/bigbluebutton#9]
I want to add this BigBlueButton properties with this package:

> The BigBlueButton server will automatically remove empty meetings that were created but have never had any users after a number of minutes specified by meetingExpireIfNoUserJoinedInMinutes defined in bigbluebutton.properties.

How to pass **meetingExpireIfNoUserJoinedInMinutes** properties while creating a meeting in this package?

**Comment by joisarjignesh** [comment]
@princerafid01 currently is not given api by bigbluebutton for bigbluebutton.properties values access and set so 
if you want to set **meetingExpireIfNoUserJoinedInMinutes** update this file  
`/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties` here
and restart the bigbluebutton server for made changes.

Note : **bigbluebutton.properties** is bigbluebutton configurations file not to any specific meeting, it will set for all meetings..
