### ISSUE TITLE
should support errorRedirectUrl

### ISSUE THREAD

**Issue by singleseeker** [joisarjignesh/bigbluebutton#93]
https://github.com/joisarjignesh/bigbluebutton/blob/1e738bb6e63116999e0db367bef4f2bbc31a15a5/src/Services/InitMeeting.php#L250

**Comment by joisarjignesh** [comment]
@singleseeker done

**Comment by singleseeker** [comment]
wow, thank you, do you have a plan to update this feature to composer?
